
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/navbar"
import { ThemeProvider } from "./Component/themeprovider";

interface RootLayoutProps {
  children: React.ReactNode;
}
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Manuel's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:RootLayoutProps) {
  return (
    <html lang="en" className=""suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <Navbar></Navbar>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
